spring:
  application:
    name: hp-forum-backend
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start-and-stop
  datasource:
    url: jdbc:postgresql://localhost:5432/hp_forum
    username: hp_forum
    password: changeMe
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
      org.hibernate.envers:
            audit_table_suffix: _aud
            store_data_at_delete: true
            audit_strategy: org.hibernate.envers.strategy.DefaultAuditStrategy
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

logging:
  level:
    org.springframework: info


