import {
  Attachment,
  AuditLog,
  CategoryDecisionKey,
  DecisionKey,
  MockDataBundle,
  Organization,
  OrganizationCategory,
  Response,
  ResponseAttachment,
  ResponseStatus,
  ResponseType,
  Survey,
  SurveyAttachment,
  SurveyCategory,
  SurveyOrganization,
  Topic,
  TopicCategory,
  TopicStatus,
  User,
  Role,
} from "./types";

export const ORGANIZATION_CATEGORIES: OrganizationCategory[] = [
  {
    id: 1,
    name: "HP Banken",
    description: "Mitglieder des HP-Beirats",
  },
  {
    id: 2,
    name: "HP IT",
    description: "Zentrale Organisationseinheit",
  },
  {
    id: 3,
    name: "Externe Partner",
  },
];

export const ORGANIZATIONS: Organization[] = [
  {
    id: 1,
    name: "Hypo Alpen",
    shortName: "HPA",
    acnClientNumber: "HPA-001",
    organizationCategoryId: 1,
  },
  {
    id: 2,
    name: "Hypo Burgenland",
    shortName: "HPB",
    acnClientNumber: "HPB-002",
    organizationCategoryId: 1,
  },
  {
    id: 3,
    name: "Hypo Capital",
    shortName: "HPC",
    acnClientNumber: "HPC-003",
    organizationCategoryId: 1,
  },
  {
    id: 4,
    name: "Hypo Donau",
    shortName: "HPD",
    acnClientNumber: "HPD-004",
    organizationCategoryId: 1,
  },
  {
    id: 5,
    name: "Hypo Elysium",
    shortName: "HPE",
    acnClientNumber: "HPE-005",
    organizationCategoryId: 1,
  },
  {
    id: 6,
    name: "Hypo Forum Bank",
    shortName: "HPF",
    acnClientNumber: "HPF-006",
    organizationCategoryId: 1,
  },
  {
    id: 7,
    name: "HP IT Forum Service",
    shortName: "HP IT",
    acnClientNumber: "HPIT-000",
    organizationCategoryId: 2,
  },
];

export const ROLES: Role[] = [
  { id: 1, name: "HP IT Service", description: "HP IT Koordination" },
  { id: 2, name: "HP Beiratsvertreter" },
  { id: 3, name: "Fachexperte" },
];

export const USERS: User[] = [
  {
    id: 1,
    name: "Anna Leitner",
    email: "anna.leitner@hpa.at",
    organizationId: 1,
    roleId: 2,
  },
  {
    id: 2,
    name: "Gerhard Paul",
    email: "gerhard.paul@hpb.at",
    organizationId: 2,
    roleId: 2,
  },
  {
    id: 3,
    name: "Julia Brantner",
    email: "julia.brantner@hpc.at",
    organizationId: 3,
    roleId: 2,
  },
  {
    id: 4,
    name: "Lukas Doerfler",
    email: "lukas.doerfler@hpd.at",
    organizationId: 4,
    roleId: 2,
  },
  {
    id: 5,
    name: "Eva Koenig",
    email: "eva.koenig@hpe.at",
    organizationId: 5,
    roleId: 2,
  },
  {
    id: 6,
    name: "Maria Peschel",
    email: "maria.peschel@hpf.at",
    organizationId: 6,
    roleId: 2,
  },
  {
    id: 7,
    name: "Alexander Kiemle",
    email: "akiemle@cs-consulting.de",
    organizationId: 7,
    roleId: 1,
  },
  {
    id: 8,
    name: "Michael Seidl",
    email: "michael.seidl@hpb.at",
    organizationId: 2,
    roleId: 3,
  },
];

export const TOPIC_CATEGORIES: TopicCategory[] = [
  { id: 1, name: "Governance" },
  { id: 2, name: "HP IT" },
  { id: 3, name: "CtB Projekte" },
  { id: 4, name: "Innovation" },
];

export const TOPIC_STATUSES: TopicStatus[] = [
  { id: 1, name: "Aktiv" },
  { id: 2, name: "In Planung" },
  { id: 3, name: "Abgeschlossen" },
];

export const TOPICS: Topic[] = [
  {
    id: 1,
    name: "HP-Expertengremien",
    shortDescription: "Koordination von Ansprechpartnern",
    topicCategoryId: 1,
    topicStatusId: 1,
    responsibleUserId: 7,
    primaryContactId: 1,
  },
  {
    id: 2,
    name: "ACN Zahlungsverkehr",
    shortDescription: "Instant Payments Roadmap",
    topicCategoryId: 3,
    topicStatusId: 1,
    responsibleUserId: 7,
    primaryContactId: 2,
    longDescription: "Koordination gemeinsamer CtB Zusatzprojekte im Zahlungsverkehr.",
  },
  {
    id: 3,
    name: "HP IT Betrieb",
    shortDescription: "Security und Infrastruktur",
    topicCategoryId: 2,
    topicStatusId: 1,
    responsibleUserId: 7,
    primaryContactId: 6,
  },
  {
    id: 4,
    name: "HP Governance",
    shortDescription: "Grundsatzthemen HP Beirat",
    topicCategoryId: 1,
    topicStatusId: 1,
    responsibleUserId: 7,
    primaryContactId: 5,
  },
  {
    id: 5,
    name: "ACN API-Plattform",
    shortDescription: "Sandbox Erweiterungen",
    topicCategoryId: 4,
    topicStatusId: 2,
    responsibleUserId: 7,
    primaryContactId: 3,
  },
  {
    id: 6,
    name: "HP Infrastruktur",
    shortDescription: "Storage Erneuerung",
    topicCategoryId: 2,
    topicStatusId: 3,
    responsibleUserId: 7,
    primaryContactId: 6,
  },
];

export const SURVEY_CATEGORIES: SurveyCategory[] = [
  { id: 1, code: "NOM", name: "Nominierung" },
  { id: 2, code: "CTB_PART", name: "Umfrage Projektbeteiligung" },
  { id: 3, code: "HPIT_DEC", name: "Beschluss HP IT Beauftragung" },
  { id: 4, code: "GEN_DEC", name: "Allgemeiner Beschluss" },
  { id: 5, code: "ACN_INIT", name: "Individuelle ACN Initiative" },
  { id: 6, code: "GEN_SURV", name: "Allgemeine Umfrage" },
];

export const DECISION_KEYS: DecisionKey[] = [
  { id: 1, code: "IND", description: "Individueller Entscheidungsschluessel" },
  { id: 2, code: "MAJ50_ALIQ", description: "50% Mehrheit aliquot" },
  { id: 3, code: "MAJ50_CTB", description: "50% Mehrheit CtB Gruppen" },
  { id: 4, code: "MAJ66_STIMM", description: "2/3 Mehrheit nach Stimmrechten" },
  { id: 5, code: "MAJ66_ALIQ", description: "2/3 Mehrheit aliquot" },
];

export const CATEGORY_DECISION_KEYS: CategoryDecisionKey[] = [
  { surveyCategoryId: 1, decisionKeyId: 1 },
  { surveyCategoryId: 2, decisionKeyId: 2 },
  { surveyCategoryId: 2, decisionKeyId: 3 },
  { surveyCategoryId: 3, decisionKeyId: 4 },
  { surveyCategoryId: 4, decisionKeyId: 4 },
  { surveyCategoryId: 5, decisionKeyId: 2 },
  { surveyCategoryId: 6, decisionKeyId: 1 },
];

export const SURVEYS: Survey[] = [
  {
    id: 1,
    surveyNumber: "2025_0001",
    name: "Nominierung Ansprechpartner Digitales KWG",
    shortDescription: "Erhebung der Ansprechpartner je Bank.",
    status: "draft",
    responseDeadline: "2025-06-21",
    createdById: 7,
    topicId: 1,
    surveyCategoryId: 1,
    createdAt: "2025-06-01",
  },
  {
    id: 2,
    surveyNumber: "2025_0002",
    name: "Beteiligung Instant Payments Clearing Release 2026",
    shortDescription: "Teilnahme und Kostenteilung ACN Projekt.",
    longDescription:
      "ACN bietet fuer 2026 ein erweitertes Instant Payments Clearing Modul. Bitte um Rueckmeldung zur Teilnahme.",
    status: "active",
    responseDeadline: "2025-06-03",
    createdById: 7,
    topicId: 2,
    surveyCategoryId: 2,
    decisionKeyId: 2,
    totalAmountGross: 450000,
    recurringCostsGrossPa: 180000,
    activationDate: "2025-05-12",
    createdAt: "2025-05-10",
  },
  {
    id: 3,
    surveyNumber: "2025_0003",
    name: "Beschluss Cloud Security Assessment 2025",
    shortDescription: "Gemeinsame HP IT Beauftragung.",
    longDescription:
      "Die HP IT moechte ein gruppenweites Security Assessment durch externen Partner durchfuehren lassen.",
    status: "active_extended",
    responseDeadline: "2025-05-15",
    extendedDeadline: "2025-05-29",
    createdById: 7,
    topicId: 3,
    surveyCategoryId: 3,
    decisionKeyId: 4,
    totalAmountGross: 320000,
    activationDate: "2025-04-15",
    createdAt: "2025-04-05",
  },
  {
    id: 4,
    surveyNumber: "2025_0004",
    name: "Beschluss HP-Beiratsordnung Update Q3",
    shortDescription: "Abstimmung zur Aktualisierung der GO.",
    status: "closed",
    responseDeadline: "2025-04-05",
    createdById: 7,
    topicId: 4,
    surveyCategoryId: 4,
    decisionKeyId: 4,
    activationDate: "2025-03-20",
    closureDate: "2025-04-04",
    createdAt: "2025-03-15",
  },
  {
    id: 5,
    surveyNumber: "2024_0042",
    name: "Interesse API Sandbox Erweiterung",
    shortDescription: "Erhebung von Interessenten.",
    status: "completed",
    responseDeadline: "2024-10-25",
    createdById: 7,
    topicId: 5,
    surveyCategoryId: 5,
    decisionKeyId: 2,
    activationDate: "2024-10-05",
    closureDate: "2024-10-24",
    createdAt: "2024-10-02",
  },
  {
    id: 6,
    surveyNumber: "2023_0017",
    name: "Beschluss Ersatz Storage Systeme 2024",
    shortDescription: "Beschaffung neuer Storage Systeme.",
    status: "archived",
    responseDeadline: "2023-02-05",
    createdById: 7,
    topicId: 6,
    surveyCategoryId: 3,
    decisionKeyId: 5,
    totalAmountGross: 780000,
    recurringCostsGrossPa: 120000,
    activationDate: "2023-01-15",
    closureDate: "2023-02-04",
    archiveDate: "2024-02-01",
    createdAt: "2023-01-12",
  },
];

export const SURVEY_ORGANIZATIONS: SurveyOrganization[] = [
  { surveyId: 1, organizationId: 1 },
  { surveyId: 1, organizationId: 2 },
  { surveyId: 1, organizationId: 3 },
  { surveyId: 1, organizationId: 4 },
  { surveyId: 1, organizationId: 5 },
  { surveyId: 1, organizationId: 6 },
  { surveyId: 2, organizationId: 1 },
  { surveyId: 2, organizationId: 2 },
  { surveyId: 2, organizationId: 3 },
  { surveyId: 2, organizationId: 4 },
  { surveyId: 2, organizationId: 5 },
  { surveyId: 3, organizationId: 1 },
  { surveyId: 3, organizationId: 2 },
  { surveyId: 3, organizationId: 3 },
  { surveyId: 3, organizationId: 4 },
  { surveyId: 3, organizationId: 5 },
  { surveyId: 3, organizationId: 6 },
  { surveyId: 4, organizationId: 1 },
  { surveyId: 4, organizationId: 2 },
  { surveyId: 4, organizationId: 3 },
  { surveyId: 4, organizationId: 4 },
  { surveyId: 4, organizationId: 5 },
  { surveyId: 4, organizationId: 6 },
  { surveyId: 5, organizationId: 1 },
  { surveyId: 5, organizationId: 2 },
  { surveyId: 5, organizationId: 3 },
  { surveyId: 5, organizationId: 4 },
  { surveyId: 6, organizationId: 1 },
  { surveyId: 6, organizationId: 2 },
  { surveyId: 6, organizationId: 3 },
  { surveyId: 6, organizationId: 4 },
  { surveyId: 6, organizationId: 5 },
  { surveyId: 6, organizationId: 6 },
];

export const RESPONSE_TYPES: ResponseType[] = [
  { id: 1, code: "OK", description: "Zustimmung" },
  { id: 2, code: "BOK", description: "Bedingte Zustimmung" },
  { id: 3, code: "NOK", description: "Ablehnung" },
  { id: 4, code: "INFO", description: "Information" },
];

export const RESPONSE_STATUSES: ResponseStatus[] = [
  { id: 1, name: "Entwurf", code: "draft" },
  { id: 2, name: "Freigegeben", code: "released" },
  { id: 3, name: "Übermittelt", code: "submitted" },
];

export const RESPONSES: Response[] = [
  {
    id: 1,
    surveyId: 1,
    organizationId: 1,
    userId: 1,
    responseStatusId: 1,
    updatedAt: "2025-06-01",
  },
  {
    id: 2,
    surveyId: 1,
    organizationId: 2,
    userId: 2,
    responseStatusId: 1,
    updatedAt: "2025-06-02",
  },
  {
    id: 3,
    surveyId: 2,
    organizationId: 1,
    userId: 1,
    responseStatusId: 3,
    responseTypeId: 1,
    responseJustification: "Teilnahme unter Vorbehalt, Budgetobergrenze 120k.",
    updatedAt: "2025-05-20",
  },
  {
    id: 4,
    surveyId: 2,
    organizationId: 2,
    userId: 8,
    delegatedForUserId: 2,
    responseStatusId: 3,
    responseTypeId: 2,
    responseJustification: "Teilnahme bei Projektkosten <= 100k.",
    delegationJustification: "Vertretung waehrend Jour Fix.",
    updatedAt: "2025-05-22",
  },
  {
    id: 5,
    surveyId: 2,
    organizationId: 3,
    userId: 3,
    responseStatusId: 3,
    responseTypeId: 3,
    updatedAt: "2025-05-25",
  },
  {
    id: 6,
    surveyId: 2,
    organizationId: 4,
    userId: 4,
    responseStatusId: 1,
    updatedAt: "2025-05-30",
  },
  {
    id: 7,
    surveyId: 2,
    organizationId: 5,
    userId: 5,
    responseStatusId: 1,
    updatedAt: "2025-05-30",
  },
  {
    id: 8,
    surveyId: 3,
    organizationId: 1,
    userId: 1,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2025-05-01",
  },
  {
    id: 9,
    surveyId: 3,
    organizationId: 2,
    userId: 2,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2025-05-03",
  },
  {
    id: 10,
    surveyId: 3,
    organizationId: 3,
    userId: 3,
    responseStatusId: 3,
    responseTypeId: 2,
    responseJustification: "Zustimmung nach Ruecksprache mit Vorstand.",
    updatedAt: "2025-05-12",
  },
  {
    id: 11,
    surveyId: 3,
    organizationId: 4,
    userId: 7,
    delegatedForUserId: 4,
    responseStatusId: 1,
    updatedAt: "2025-05-20",
  },
  {
    id: 12,
    surveyId: 3,
    organizationId: 5,
    userId: 7,
    delegatedForUserId: 5,
    responseStatusId: 1,
    delegationJustification: "Vertretung wegen Urlaub.",
    updatedAt: "2025-05-21",
  },
  {
    id: 13,
    surveyId: 3,
    organizationId: 6,
    userId: 6,
    responseStatusId: 3,
    responseTypeId: 3,
    responseJustification: "Keine Ressourcen in 2025 verfuegbar.",
    updatedAt: "2025-05-10",
  },
  {
    id: 14,
    surveyId: 4,
    organizationId: 1,
    userId: 1,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2025-03-25",
  },
  {
    id: 15,
    surveyId: 4,
    organizationId: 2,
    userId: 2,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2025-03-26",
  },
  {
    id: 16,
    surveyId: 4,
    organizationId: 3,
    userId: 3,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2025-03-27",
  },
  {
    id: 17,
    surveyId: 4,
    organizationId: 4,
    userId: 4,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2025-03-28",
  },
  {
    id: 18,
    surveyId: 4,
    organizationId: 5,
    userId: 5,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2025-03-28",
  },
  {
    id: 19,
    surveyId: 4,
    organizationId: 6,
    userId: 6,
    responseStatusId: 3,
    responseTypeId: 2,
    responseJustification: "Zustimmung unter Auflagen.",
    updatedAt: "2025-03-29",
  },
  {
    id: 20,
    surveyId: 5,
    organizationId: 1,
    userId: 1,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2024-10-10",
  },
  {
    id: 21,
    surveyId: 5,
    organizationId: 2,
    userId: 2,
    responseStatusId: 3,
    responseTypeId: 2,
    responseJustification: "Budgetfreigabe noch ausstaendig.",
    updatedAt: "2024-10-12",
  },
  {
    id: 22,
    surveyId: 5,
    organizationId: 3,
    userId: 3,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2024-10-15",
  },
  {
    id: 23,
    surveyId: 5,
    organizationId: 4,
    userId: 7,
    delegatedForUserId: 4,
    responseStatusId: 1,
    updatedAt: "2024-10-18",
  },
  {
    id: 24,
    surveyId: 6,
    organizationId: 1,
    userId: 1,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2023-01-20",
  },
  {
    id: 25,
    surveyId: 6,
    organizationId: 2,
    userId: 2,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2023-01-20",
  },
  {
    id: 26,
    surveyId: 6,
    organizationId: 3,
    userId: 3,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2023-01-21",
  },
  {
    id: 27,
    surveyId: 6,
    organizationId: 4,
    userId: 4,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2023-01-21",
  },
  {
    id: 28,
    surveyId: 6,
    organizationId: 5,
    userId: 5,
    responseStatusId: 3,
    responseTypeId: 2,
    responseJustification: "Zustimmung vorbehaltlich finaler Kostenaufteilung.",
    updatedAt: "2023-01-22",
  },
  {
    id: 29,
    surveyId: 6,
    organizationId: 6,
    userId: 6,
    responseStatusId: 3,
    responseTypeId: 1,
    updatedAt: "2023-01-23",
  },
];

export const ATTACHMENTS: Attachment[] = [
  { id: 1, filename: "go_update.pdf", filetype: "application/pdf", filesize: 245678 },
  { id: 2, filename: "security_scope.docx", filetype: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", filesize: 102400 },
];

export const SURVEY_ATTACHMENTS: SurveyAttachment[] = [
  { surveyId: 3, attachmentId: 2 },
  { surveyId: 4, attachmentId: 1 },
];

export const RESPONSE_ATTACHMENTS: ResponseAttachment[] = [];

export const AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    entityName: "Survey",
    entityId: 3,
    changedBy: 7,
    timestamp: "2025-05-16T09:30:00Z",
    changes: "responseDeadline extended to 2025-05-29",
  },
  {
    id: 2,
    entityName: "Response",
    entityId: 12,
    changedBy: 7,
    timestamp: "2025-05-21T14:15:00Z",
    changes: "delegatedForUserId set to 5",
  },
];

export const MOCK_DATA: MockDataBundle = {
  organizationCategories: ORGANIZATION_CATEGORIES,
  organizations: ORGANIZATIONS,
  roles: ROLES,
  users: USERS,
  topicCategories: TOPIC_CATEGORIES,
  topicStatuses: TOPIC_STATUSES,
  topics: TOPICS,
  surveyCategories: SURVEY_CATEGORIES,
  decisionKeys: DECISION_KEYS,
  categoryDecisionKeys: CATEGORY_DECISION_KEYS,
  surveys: SURVEYS,
  surveyOrganizations: SURVEY_ORGANIZATIONS,
  responseTypes: RESPONSE_TYPES,
  responseStatuses: RESPONSE_STATUSES,
  responses: RESPONSES,
  attachments: ATTACHMENTS,
  surveyAttachments: SURVEY_ATTACHMENTS,
  responseAttachments: RESPONSE_ATTACHMENTS,
  auditLogs: AUDIT_LOGS,
};
export function createMockDataBundle(): MockDataBundle {
  if (typeof structuredClone === "function") {
    return structuredClone(MOCK_DATA);
  }

  return JSON.parse(JSON.stringify(MOCK_DATA)) as MockDataBundle;
}

